Rip out buggy repetition detection and replace with temp C code.

diff --git a/vivado/scripts/timingruns b/vivado/scripts/timingruns
--- a/vivado/scripts/timingruns
+++ b/vivado/scripts/timingruns
@@ -7,21 +7,20 @@ fi
 seed=`cat ../random_constant.vh | awk ' { print $3 } '`
 if [ "$seed" = '' ]
 then
-    printf '%s: cannot find start seed\n' $0 1>&2
+    printf '%s: cannot find previous seed\n' $0 1>&2
     exit 1
 fi
-seed=`expr $seed + 1`
 runno=0
 while [ $runno -lt 10 ]
 do
+    seed=`hexdump -vn4 -e'"%08X" 1 "\n"' /dev/urandom`
     tmppath=~/tmp/timing/run_$seed
     rm -fr $tmppath
     mkdir -p $tmppath
-    printf 'Starting run %d\n' $seed
-    printf '`define RANDOM_CONSTANT %d\n' $seed > ../random_constant.vh
+    printf 'Starting run %d\n' $runno
+    printf '`define RANDOM_CONSTANT '"'"'h%s\n' $seed > ../random_constant.vh
     (make distclean && make create_hardware) > $tmppath/build.log 2>&1
     cp ./numbat/numbat_1.runs/impl_1/*.rpt $tmppath
-    seed=`expr $seed + 1`
     runno=`expr $runno + 1`
 done
 printf 'Done.\n'
